require:
  - rubocop-rake

inherit_gem:
  rubocop-inst:
  - rubocop.yml
  - rubocop-rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 2.7
  Exclude:
    - 'gemfiles/*'

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/activerecord-pg-extensions.rb

RSpec/ContextWording:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false