name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.3'
          - '3.4'
        lockfile:
          - 'Gemfile.rails-7.2.lock'
          - 'Gemfile.lock' # rails-8.0
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      BUNDLE_LOCKFILE: ${{ matrix.lockfile }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        env:
          BUNDLE_NO_PRUNE: true
      - name: Run tests
        run: bin/rspec
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASSWORD: postgres

  lint:
    runs-on: ubuntu-latest
    env:
      BUNDLE_LOCKFILE: "Gemfile.lock"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - name: Run RuboCop
        run: bin/rubocop
        timeout-minutes: 2
  
  lint-lockfile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Ensure Lockfiles are Synchronized
        run: bundle install && bundle check
